---
- name: Firewall rule to allow ssh_ca service on TCP port 8080
  win_firewall_rule:
    name: "{{ssh_ca_service_name}}"
    localport: 8080
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: yes

- name: Check ssh_ca service state
  win_service:
    name: "{{ssh_ca_service_name}}"
  register: ssh_ca_service

- name: Stop the old ssh_ca service if installed
  win_service:
    name: "{{ssh_ca_service_name}}"
    state: stopped
  when: ssh_ca_service.exists

- name: Create SSH Certificate Authority directory
  win_file:
    path: "{{ssh_ca_bin_dir}}"
    state: directory

- name: Copy over ssh_ca binary
  win_copy:
    src: ssh_ca.exe
    dest: "{{ssh_ca_bin_dir}}\\ssh_ca.exe"

- name: Uninstall the old ssh_ca service if installed
  win_shell: ./ssh_ca.exe remove
  args:
    chdir: "{{ssh_ca_bin_dir}}"
  when: ssh_ca_service.exists

- name: Install the ssh_ca service
  win_shell: ./ssh_ca.exe install
  args:
    chdir: "{{ssh_ca_bin_dir}}"

- name: Start the ssh_ca service
  win_service:
    name: "{{ssh_ca_service_name}}"
    start_mode: auto
    state: started
